DEV_HUB_ALIAS="Rishabhdevhub"
SCRATCH_ORG_ALIAS="Rishabhscratch"
PACKAGENAME="demoRishabhGitPack"
QA_ORG_ALIAS="RishabhQAURL"
DEV_HUB_ALIAS1="Meghdevhub"
SCRATCH_ORG_ALIAS1="MeghgitAssignscratch"
PACKAGENAME1="demoGitMegheshv3.3.3"
QA_ORG_ALIAS1="MeghmyQA"
